// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: proto/burnafter.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreRequest represents a request from the client to store a new secret
type StoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret name (id to refetence it)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Secret value to store
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Inactivity TTL in seconds (secret expires if not accessed for this duration)
	TtlSeconds int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Compile-time nonce from client
	ClientNonce string `protobuf:"bytes,4,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	// Optional: absolute expiration time in seconds from now (0 = no absolute expiration)
	AbsoluteExpirationSeconds int64 `protobuf:"varint,5,opt,name=absolute_expiration_seconds,json=absoluteExpirationSeconds,proto3" json:"absolute_expiration_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_burnafter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *StoreRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *StoreRequest) GetClientNonce() string {
	if x != nil {
		return x.ClientNonce
	}
	return ""
}

func (x *StoreRequest) GetAbsoluteExpirationSeconds() int64 {
	if x != nil {
		return x.AbsoluteExpirationSeconds
	}
	return 0
}

// StoreResponse returns the results of storing a secret
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_burnafter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get request is a request from the client to retrieve a secre
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret name to retrieve
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Client nonce, a baked value in the client somewhat hidden
	ClientNonce   string `protobuf:"bytes,2,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"` // Compile-time nonce from client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_burnafter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRequest) GetClientNonce() string {
	if x != nil {
		return x.ClientNonce
	}
	return ""
}

// GetResponse returns the results when retrieving the secret.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_burnafter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PingRequest an emptyu request to check if the3 server is alive
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_burnafter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{4}
}

// Response when the server is running
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_burnafter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burnafter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_burnafter_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_proto_burnafter_proto protoreflect.FileDescriptor

const file_proto_burnafter_proto_rawDesc = "" +
	"\n" +
	"\x15proto/burnafter.proto\x12\tburnafter\"\xbe\x01\n" +
	"\fStoreRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12!\n" +
	"\fclient_nonce\x18\x04 \x01(\tR\vclientNonce\x12>\n" +
	"\x1babsolute_expiration_seconds\x18\x05 \x01(\x03R\x19absoluteExpirationSeconds\"?\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fclient_nonce\x18\x02 \x01(\tR\vclientNonce\"U\n" +
	"\vGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive2\xb6\x01\n" +
	"\tBurnAfter\x12:\n" +
	"\x05Store\x12\x17.burnafter.StoreRequest\x1a\x18.burnafter.StoreResponse\x124\n" +
	"\x03Get\x12\x15.burnafter.GetRequest\x1a\x16.burnafter.GetResponse\x127\n" +
	"\x04Ping\x12\x16.burnafter.PingRequest\x1a\x17.burnafter.PingResponseB4Z2github.com/carabiner-dev/burnafter/internal/commonb\x06proto3"

var (
	file_proto_burnafter_proto_rawDescOnce sync.Once
	file_proto_burnafter_proto_rawDescData []byte
)

func file_proto_burnafter_proto_rawDescGZIP() []byte {
	file_proto_burnafter_proto_rawDescOnce.Do(func() {
		file_proto_burnafter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_burnafter_proto_rawDesc), len(file_proto_burnafter_proto_rawDesc)))
	})
	return file_proto_burnafter_proto_rawDescData
}

var file_proto_burnafter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_burnafter_proto_goTypes = []any{
	(*StoreRequest)(nil),  // 0: burnafter.StoreRequest
	(*StoreResponse)(nil), // 1: burnafter.StoreResponse
	(*GetRequest)(nil),    // 2: burnafter.GetRequest
	(*GetResponse)(nil),   // 3: burnafter.GetResponse
	(*PingRequest)(nil),   // 4: burnafter.PingRequest
	(*PingResponse)(nil),  // 5: burnafter.PingResponse
}
var file_proto_burnafter_proto_depIdxs = []int32{
	0, // 0: burnafter.BurnAfter.Store:input_type -> burnafter.StoreRequest
	2, // 1: burnafter.BurnAfter.Get:input_type -> burnafter.GetRequest
	4, // 2: burnafter.BurnAfter.Ping:input_type -> burnafter.PingRequest
	1, // 3: burnafter.BurnAfter.Store:output_type -> burnafter.StoreResponse
	3, // 4: burnafter.BurnAfter.Get:output_type -> burnafter.GetResponse
	5, // 5: burnafter.BurnAfter.Ping:output_type -> burnafter.PingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_burnafter_proto_init() }
func file_proto_burnafter_proto_init() {
	if File_proto_burnafter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_burnafter_proto_rawDesc), len(file_proto_burnafter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_burnafter_proto_goTypes,
		DependencyIndexes: file_proto_burnafter_proto_depIdxs,
		MessageInfos:      file_proto_burnafter_proto_msgTypes,
	}.Build()
	File_proto_burnafter_proto = out.File
	file_proto_burnafter_proto_goTypes = nil
	file_proto_burnafter_proto_depIdxs = nil
}
